### ISSUE TITLE
Cant push to device or all devices

### ISSUE THREAD

**Issue by pleasedropin** [xarnze/sublimepushbullet#2]
Hi!
Trying out Your interesting package subliempushbullet. It sounds very promising.
However a couple of issues occur for me. I using Win7 , ST build 3083

When trying to push to device I saw "getting devices" in the statusbar.
However no list is shown som I cant choose a device to push to.
Console message:
Traceback (most recent call last):
  File "Pushbullet in C:...\Sublime Text 3\Installed Packages\Pushbullet.sublime-package", line 61, in <lambda>
  File "Pushbullet in C:...\Sublime Text 3\Installed Packages\Pushbullet.sublime-package", line 70, in handle_threads
KeyError: 'nickname'

And when I try to push to all devices nothing happens but the console message is shown:
Traceback (most recent call last):
  File "C:...\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "Pushbullet in C:...\Sublime Text 3\Installed Packages\Pushbullet.sublime-package", line 20, in run
TypeError: send_note() missing 1 required positional argument: 'view'

Kind regards, 
Jörgen Sköld

**Comment by pleasedropin** [comment]
I'm so sorry - the first problem with choosing a speicfic device stems from a device in my devicelist where no nickname was entered. So forget that one.
The function to push to all devices still doesnt work for me.

Kind regards,
Jörgen Sköld

**Comment by xarnze** [comment]
Ok, are you able to push to a specific device?

**Comment by pleasedropin** [comment]
Hi !

Yeah, once I figured out and corrected the missing nickname for the device in the list it works when choosing one device.

The list is shown, I pick a device and the selected text is pushed to the chosen device.

But I still have no luck when trying to push to all devices.

/js

Från: Aaron Polley [mailto:notifications@github.com] 
Skickat: den 10 augusti 2015 12:34
Till: xarnze/sublimepushbullet sublimepushbullet@noreply.github.com
Kopia: pleasedropin jorgen.skold@icloud.com
Ämne: Re: [sublimepushbullet] Cant push to device or all devices (#2)

Ok, are you able to push to a specific device?

**Comment by xarnze** [comment]
Could you try and push to all devices and post the console output?

**Comment by pleasedropin** [comment]
Sure:

Traceback (most recent call last):

  File "C:...\Sublime Text 3\sublime_plugin.py", line 556, in run_

```
return self.run(edit)
```

  File "Pushbullet in C:...\Sublime Text 3\Installed Packages\Pushbullet.sublime-package", line 20, in run

TypeError: send_note() missing 1 required positional argument: 'view'

/js

Från: Aaron Polley [mailto:notifications@github.com] 
Skickat: den 10 augusti 2015 12:54
Till: xarnze/sublimepushbullet sublimepushbullet@noreply.github.com
Kopia: pleasedropin jorgen.skold@icloud.com
Ämne: Re: [sublimepushbullet] Cant push to device or all devices (#2)

Could you try and push to all devices and post the console output?

**Comment by xarnze** [comment]
Fixed by de57ed9, I'll build a new release and you should get an update in the next hour

**Comment by pleasedropin** [comment]
Great! What a quick response!

Thank you so much!

/js

Från: Aaron Polley [mailto:notifications@github.com] 
Skickat: den 10 augusti 2015 13:24
Till: xarnze/sublimepushbullet sublimepushbullet@noreply.github.com
Kopia: pleasedropin jorgen.skold@icloud.com
Ämne: Re: [sublimepushbullet] Cant push to device or all devices (#2)

Fixed by  https://github.com/xarnze/sublimepushbullet/commit/de57ed9cb2ffd88fe663b318e5ecfef8657436f8 de57ed9, I'll build a new release and you should get an update in the next hour

**Comment by pleasedropin** [comment]
Works great.

thanks!

/js

Från: Aaron Polley [mailto:notifications@github.com] 
Skickat: den 10 augusti 2015 14:32
Till: xarnze/sublimepushbullet sublimepushbullet@noreply.github.com
Kopia: pleasedropin jorgen.skold@icloud.com
Ämne: Re: [sublimepushbullet] Cant push to device or all devices (#2)

Closed #2 https://github.com/xarnze/sublimepushbullet/issues/2 .
